TITLE = 'Placeholder Title'

DISPLAY_WIDTH = 1280
DISPLAY_HEIGHT = 960

FPS = 60

TILESIZE = 16
GRID_WIDTH = DISPLAY_WIDTH / TILESIZE
GRID_HEIGHT = DISPLAY_HEIGHT / TILESIZE

PLAYER_SPEED = TILESIZE * 12
PLAYER_JUMP = TILESIZE * 24
GRAV_ACC = TILESIZE * 40
