TITLE = 'Placeholder Title'

DISPLAY_WIDTH = 1280
DISPLAY_HEIGHT = 960

FPS = 30

TILESIZE = 16
GRID_WIDTH = DISPLAY_WIDTH / TILESIZE
GRID_HEIGHT = DISPLAY_HEIGHT / TILESIZE

PLAYER_SPEED = TILESIZE * 12
GRAV_ACC = TILESIZE * 32
